spring:
  datasource:
    url: ${RDS_URL:jdbc:mysql://localhost:3306/bunny_care}
    username: ${RDS_USER_NAME:admin}
    password: ${RDS_PASSWORD:1111}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  log:
    file-path: ${LOG_UPLOAD_PATH:C:\logs}

file:
  upload:
    path : ${FILE_UPLOAD_PATH:C:\images}

jwt:
  access:
    hour: ${ACCESS_HOUR:12}
  refresh:
    hour: ${REFRESH_HOUR:24}
  secret: ${JWT_SECRET:QWER}

api:
  version : v1

management:
  endpoints:
    web:
      exposure:
        include: health, info, loggers

